// ─── Default settings ─────────────────────────────────────────────────────────
export const DEFAULT_SETTINGS = {
  pagination:         true,
  detectAPI:          true,
  detectGraphQL:      true,
  encodingFix:        true,
  infiniteScroll:     false,
  endlessButton:      false,
  lazyLoad:           true,
  shadowDOM:          false,
  csrfHandling:       false,
  cookieLogin:        false,
  persistentCookies:  false,
  attachmentDownload: false,
  formUploadDetect:   false,
  antibotMode:        false,
  cloudflareDetect:   false,
  aspShieldBypass:    false,
};

// ─── Settings metadata ────────────────────────────────────────────────────────
export const SETTING_META = {
  pagination:         { label: "Auto Detect Pagination",        badge: "CORE",    warn: null,
    desc: "Automatically follows 'Next Page' links and increments page numbers. Enables multi-page scraping without manually listing URLs." },
  detectAPI:          { label: "Detect Hidden API Endpoints",   badge: "CORE",    warn: null,
    desc: "Scans JavaScript bundles for fetch/axios/XHR calls to find JSON data APIs. Results appear in the API tab after scraping." },
  detectGraphQL:      { label: "Detect GraphQL Requests",       badge: "CORE",    warn: null,
    desc: "Searches for GraphQL endpoint URLs in JS source code and network call patterns. Useful for React/Next.js apps that use Apollo." },
  encodingFix:        { label: "Fix Encoding (charset repair)",  badge: "CORE",    warn: null,
    desc: "Re-fetches pages as raw bytes when a non-UTF-8 charset is declared. Fixes garbled characters on Japanese, Chinese, Eastern-European pages." },
  infiniteScroll:     { label: "Infinite Scroll Detection",      badge: "DETECT",  warn: "Detects scroll signals only — actual scrolling requires a real browser (Playwright/Puppeteer). Results include confidence score and detected signals.",
    desc: "Detects IntersectionObserver usage, infinite-scroll library loading, sentinel elements, scroll event listeners, and API pagination tokens. Reports confidence level and the specific signals found." },
  endlessButton:      { label: "Load-More Button Detection",     badge: "DETECT",  warn: "Detects 'Load More' buttons only — clicking them requires a real browser (Playwright/Puppeteer). Results include button selector and text.",
    desc: "Finds 'Load More', 'Show More', 'View More' buttons by exact text match, CSS class patterns (load-more, loadMore), and data-action attributes. Reports the CSS selector so you can target it in Playwright." },
  lazyLoad:           { label: "Lazy Image Loading",             badge: "EXTRACT", warn: null,
    desc: "Swaps data-src / data-lazy / data-original attributes to real src before extracting images. Required for sites using LazyLoad.js or similar." },
  shadowDOM:          { label: "Shadow DOM Scraping",            badge: "EXTRACT", warn: null,
    desc: "Recursively traverses declarative Shadow DOM templates, live shadow roots (when accessible), JSON script blocks, and Web Component slot/part attributes. Supports nested shadow roots up to 10 levels deep." },
  csrfHandling:       { label: "CSRF Token Extraction",          badge: "AUTH",    warn: null,
    desc: "Reads CSRF/authenticity tokens from meta tags and hidden form fields. Extracted tokens are included in result rows so you can use them in POST requests." },
  cookieLogin:        { label: "Cookie-Based Login Support",     badge: "AUTH",    warn: null,
    desc: "Injects stored session cookies into proxy requests. Use with Persistent Cookies to access pages that require authentication via cookie sessions." },
  persistentCookies:  { label: "Persistent Cookie Storage",      badge: "AUTH",    warn: null,
    desc: "Saves cookies received from each response to localStorage. Combined with Cookie Login, this keeps your session alive across multiple scraping runs." },
  attachmentDownload: { label: "File Attachment Detection",      badge: "FILE",    warn: null,
    desc: "Scans all links for downloadable files (PDF, ZIP, DOCX, MP4, etc.) via href extension, <a download> attribute, and data-file attributes. Normalizes relative URLs to absolute and reports file type and detection source." },
  formUploadDetect:   { label: "File Upload Form Detection",     badge: "FILE",    warn: null,
    desc: "Finds HTML forms that contain <input type='file'> fields. Reports the form action URL, method, and field names as extra rows in the result." },
  antibotMode:        { label: "Anti-Bot Mode (Advanced)",        badge: "SHIELD",  warn: null,
    desc: "Full human-like request simulation: rotating User-Agent (Chrome/Firefox/Edge/Safari), complete browser headers (Accept, Sec-Fetch-*, Sec-CH-UA), bimodal delay (1.5–9s), cookie jar per-domain, and exponential backoff between retries." },
  cloudflareDetect:   { label: "Cloudflare Challenge Detection", badge: "SHIELD",  warn: null,
    desc: "Detects Cloudflare 'Just a moment…' pages via pattern matching, HTTP 403/503 status codes, meta-refresh redirects, and thin-body signatures. Returns cloudflareProtected: true and the specific detection reason." },
  aspShieldBypass:    { label: "ASP.NET ViewState Extraction",   badge: "SHIELD",  warn: null,
    desc: "Extracts __VIEWSTATE, __EVENTVALIDATION, and __VIEWSTATEGENERATOR tokens from ASP.NET pages. Token values are added as result rows for use in POST requests." },
};

// ─── Badge color map ──────────────────────────────────────────────────────────
export const BADGE_COLORS = {
  CORE:    { bg: "#e3f2fd", color: "#1565c0" },
  DETECT:  { bg: "#fff8e1", color: "#f57f17" },
  EXTRACT: { bg: "#f3e5f5", color: "#7b1fa2" },
  AUTH:    { bg: "#fce4ec", color: "#c62828" },
  FILE:    { bg: "#e8f5e9", color: "#2e7d32" },
  SHIELD:  { bg: "#ede7f6", color: "#4527a0" },
};
